dockerfile 수정

diff --git a/cocktail-app/Dockerfile b/cocktail-app/Dockerfile
--- a/cocktail-app/Dockerfile
+++ b/cocktail-app/Dockerfile
@@ -1,17 +1,49 @@
-FROM --platform=linux/amd64 node:16-alpine
+FROM node:16-alpine AS base
+# --platform=linux/amd64
+FROM base AS deps
+# production / development
+
+RUN apk add --no-cache libc6-compat
 
 WORKDIR /app
 
-COPY package*.json ./
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock package-lock.json* ./
 
-RUN npm ci
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-RUN npm run build
+# RUN npm ci
+RUN yarn build
 
-ENV NODE_ENV=production
+FROM base AS runner
+WORKDIR /app
 
-EXPOSE 3000
+ENV NODE_ENV development
 
-CMD ["npm", "start"]
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+ENV PATH="/usr/local/bin/yarn:${PATH}"
+
+RUN ls -l ./ \
+  && ls -l ./.next/ \
+  && ls -l ./.next/static
+
+USER nextjs
+
+CMD [ "node", "server.js" ]
